from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from app.database import get_db
from app.models import Test, Question
from app.schemas import TestBase, QuestionBase, Test as TestSchema, GenerateTestRequest, EvaluateRequest, FullEvaluateRequest
from app.services import gemini_service
from app.routers.auth import get_current_user
from app import models
import json
import random

router = APIRouter(
    prefix="/tests",
    tags=["tests"]
)

@router.post("/generate", response_model=TestSchema)
def generate_new_test(
    request: GenerateTestRequest,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    """
    Generate a new test using Google Gemini API based on the category.
    """
    category = request.category.upper()
    existing_count = db.query(Test).filter(Test.category == category).count()
    new_title = f"{category} Practice Test {existing_count + 1}"
    
    questions_data = []
    description = ""
    duration = 600

    if category == "OIR":
        description = "Officer Intelligence Rating logic test generated by AI."
        duration = 900
        raw_questions = gemini_service.generate_oir_questions(count=25)
        for q in raw_questions:
            questions_data.append({
                "text": q.get("text"),
                "options": json.dumps(q.get("options", [])),
                "correct_answer": q.get("correct_answer")
            })

    elif category == "PPDT":
        description = "AI Generated Picture Perception Scenario."
        duration = 270
        scenario = gemini_service.generate_ppdt_scenario()
        img_idx = random.randint(1, 10)
        questions_data.append({
            "text": f"Evaluate the scenario: {scenario.get('description')}", 
            "options": json.dumps([f"/ppdt/ppdt-{img_idx}.webp"]), 
            "correct_answer": ""
        })

    elif category == "WAT":
        description = "Word Association Test generated by AI."
        duration = 900
        words = gemini_service.generate_wat_words(count=15)
        for word in words:
            questions_data.append({
                "text": word,
                "options": "[]",
                "correct_answer": ""
            })

    elif category == "SRT":
        description = "Situation Reaction Test generated by AI."
        duration = 1800
        situations = gemini_service.generate_srt_situations(count=10)
        for sit in situations:
            questions_data.append({
                "text": sit,
                "options": "[]",
                "correct_answer": ""
            })

    elif category == "GTO":
        description = "Group Testing Officer tasks: GD topics and GPE cases."
        duration = 1800
        tasks = gemini_service.generate_gto_tasks(count=2)
        for t in tasks:
            questions_data.append({
                "text": f"[{t.get('type')}] {t.get('title')}: {t.get('description')}",
                "options": json.dumps({"type": t.get("type"), "title": t.get("title")}),
                "correct_answer": ""
            })
    
    else:
        raise HTTPException(status_code=400, detail="Invalid category. Supported: OIR, PPDT, WAT, SRT")

    if not questions_data:
        raise HTTPException(status_code=500, detail="Failed to generate questions from AI service.")

    # Save to DB
    new_test = Test(
        title=new_title,
        category=category,
        description=description,
        duration_seconds=duration
    )
    db.add(new_test)
    db.commit()
    db.refresh(new_test)

    for q_data in questions_data:
        q = Question(test_id=new_test.id, **q_data)
        db.add(q)
    
    db.commit()
    return new_test

@router.get("/", response_model=List[TestSchema])
def read_tests(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    # Helper to check and create specific test categories if they don't exist
    def create_if_missing(category, title, desc, duration, questions_data):
        if not db.query(Test).filter(Test.category == category).first():
            new_test = Test(
                title=title,
                category=category,
                description=desc,
                duration_seconds=duration
            )
            db.add(new_test)
            db.commit()
            db.refresh(new_test)
            
            for q_data in questions_data:
                q = Question(test_id=new_test.id, **q_data)
                db.add(q)
            db.commit()

    # Initialize Sample Data only if database is empty
    if not db.query(Test).first():
        create_if_missing(
            "OIR", 
            "OIR Practice Test 1", 
            "Officer Intelligence Rating practice test. Logical reasoning.", 
            900,
            [
                {"text": "Find the odd one out.", "options": '["Apple", "Banana", "Carrot", "Grape"]', "correct_answer": "Carrot"},
                {"text": "If CAT is coded as 3120, how is DOG coded?", "options": '["4157", "4158", "4159", "4160"]', "correct_answer": "4157"}
            ]
        )
        
        create_if_missing(
            "PPDT", 
            "PPDT Visualization 1", 
            "Picture Perception and Discussion Test. View image for 30s.", 
            270,
            [{"text": "Describe the picture shown.", "options": '["/ppdt/ppdt-1.webp"]', "correct_answer": ""}]
        )

        create_if_missing(
            "WAT", 
            "WAT Set 1", 
            "Word Association Test. Write the first thought that comes to your mind.", 
            900,
            [
                {"text": "COURAGE", "options": '[]', "correct_answer": ""},
                {"text": "FAILURE", "options": '[]', "correct_answer": ""},
                {"text": "LEADER", "options": '[]', "correct_answer": ""}
            ]
        )

        create_if_missing(
            "SRT", 
            "SRT Set 1", 
            "Situation Reaction Test. Write your response to the situation.", 
            1800,
            [
                {"text": "He was on his way to the exam hall and saw an accident using his bike.", "options": '[]', "correct_answer": ""},
                {"text": "He was appointed as the captain of a losing team.", "options": '[]', "correct_answer": ""}
            ]
        )

        create_if_missing(
            "GTO",
            "GTO Indoor Tasks 1",
            "GD and GPE practice sessions for group evaluation.",
            1800,
            [
                {
                    "text": "[GD] Impact of Social Media: Discuss the pros and cons of social media on youth.",
                    "options": '{"type": "GD", "title": "Impact of Social Media"}',
                    "correct_answer": ""
                },
                {
                    "text": "[GPE] The Flood Rescue: A village is flooded and you must plan a rescue operation.",
                    "options": '{"type": "GPE", "title": "The Flood Rescue"}',
                    "correct_answer": ""
                }
            ]
        )

    return db.query(Test).all()

@router.get("/{test_id}", response_model=TestSchema)
def read_test(
    test_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    test = db.query(Test).filter(Test.id == test_id).first()
    if test is None:
        raise HTTPException(status_code=404, detail="Test not found")
    return test

@router.delete("/{test_id}")
def delete_test(
    test_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    test = db.query(Test).filter(Test.id == test_id).first()
    if test is None:
        raise HTTPException(status_code=404, detail="Test not found")
    db.delete(test)
    db.commit()
    return {"detail": "Test deleted"}

@router.post("/evaluate")
def evaluate_response(
    request: EvaluateRequest,
    current_user: models.User = Depends(get_current_user)
):
    """
    Evaluate a candidate's response to an SSB test using AI.
    """
    evaluation = gemini_service.evaluate_test_response(
        category=request.category,
        question=request.question,
        response=request.response
    )
    return evaluation

@router.post("/{test_id}/evaluate-all")
def evaluate_full(
    test_id: int, 
    request: FullEvaluateRequest, 
    db: Session = Depends(get_db), 
    current_user: models.User = Depends(get_current_user)
):
    """
    Evaluate all responses in a full test session using AI for holistic insights.
    """
    test = db.query(Test).filter(Test.id == test_id).first()
    if not test:
        raise HTTPException(status_code=404, detail="Test not found")
        
    questions_responses = []
    for q_id, resp in request.responses.items():
        q = db.query(Question).filter(Question.id == int(q_id)).first()
        if q:
            questions_responses.append({"question": q.text, "response": resp})
            
    if not questions_responses:
         raise HTTPException(status_code=400, detail="No valid responses submitted for evaluation.")

    evaluation = gemini_service.evaluate_full_test(request.category, questions_responses)
    return evaluation


@router.post("/sdt/analyze")
def analyze_sdt(
    request: dict,
    current_user: models.User = Depends(get_current_user)
):
    """
    Analyze a candidate's Self Description Test (SDT) using AI psychologist.
    """
    result = gemini_service.analyze_sdt(
        parents=request.get("parents", ""),
        teachers=request.get("teachers", ""),
        friends=request.get("friends", ""),
        self_view=request.get("self_view", ""),
        qualities_to_develop=request.get("qualities_to_develop", ""),
    )
    return result
